version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: modern_space_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: modern_space
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: modern_space_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:secretpassword@db:5432/modern_space
    depends_on:
      - db
    restart: always

volumes:
  pgdata: